version: '3.8'

services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  # PHP-FPM service with Laravel
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - .:/var/www
    expose:
      - "9000"
